### ISSUE TITLE
Add --info and --debug options to ionic

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#1041]
_From @Hypher on June 6, 2016 16:22_

Pass --info and --debug flags to gradlew to help debugging build problems.
Note that gradlew output on such problems ask the user to use theses. (ionic not supporting them is a bit confusing)

_Copied from original issue: driftyco/ionic#6781_

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As this is an issue with the ionic-cli and not the framework i will be moving this issue to the ionic-cli repo. Thanks for using Ionic!

**Comment by mirkonasato** [comment]
Ideally passing `--debug` should also result in `--dev` being passed to [ionic-app-scripts](https://github.com/driftyco/ionic-app-scripts#all-available-tasks).

It's pretty difficult to debug errors with a minified and uglified javascript bundle.

**Comment by dwieeb** [comment]
Is this still relevant? In the latest CLI, you can pass args to Cordova. See the examples with `ionic cordova run --help`.

**Comment by Hypher** [comment]
I don't know if it still relevant. The point was that ionic did not pass --info or --debug flags to gradlew. Maybe an issue of cordova, in such case you have to link and track such an issue here. Or maybe an issue of ionic.
Cordova seems to be able to pass gradle args:
https://cordova.apache.org/docs/en/latest/guide/platforms/android/#setting-gradle-properties
Then maybe it would be fine if passing --debug to ionic-cli would end in appending `-- --gradleArg=--debug` to cordova command line? (although I don't know if it ever works this way)

I'm out of this business now, but I think introducing an intentional bug in the graddle script and trying to run `ionic build` would confirm or infirm what you supposed.
