### ISSUE TITLE
Get NPM Link working on Ionic Repo

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/ionic-cli#1075]
Right now, There isn't a good way to get `npm link` working for the Ionic repo.

We execute the following process to test local builds.

```
gulp package build —typecheck
** delete contents of test project's node_modules/ionic-angular dir **
** copy and paste contents of ionic/dist to test project's node_modules/ionic-angulardir **
```

It is not the best process.  `npm link` would work much better but the build process does not support it right now.

**Comment by rapropos** [comment]
I have no idea how this affects browserify, but when using webpack, I banged into [this issue](https://github.com/webpack/webpack/issues/554) and [this issue](https://github.com/npm/npm/issues/7742) and [this issue](https://github.com/webpack/webpack/issues/2134), which all resulted in rather mysterious bugs due to two angulars being included in the build. However, adding the following aliases to the test project (the `npm link` consumer) seems to have resolved the issue, allowing me to use an `npm link`ed ionic. I don't know if this is the problem you're referencing, but since I spent the last day and a half banging my head against the wall on this, I thought I would at least share what I learned.

```
      "@angular/common": path.resolve(__dirname, "node_modules/@angular/common"),
      "@angular/compiler": path.resolve(__dirname, "node_modules/@angular/compiler"),
      "@angular/core": path.resolve(__dirname, "node_modules/@angular/core"),
      "@angular/forms": path.resolve(__dirname, "node_modules/@angular/forms"),
      "@angular/http": path.resolve(__dirname, "node_modules/@angular/http"),
      "@angular/platform-browser": path.resolve(__dirname, "node_modules/@angular/platform-browser"),
      "@angular/platform-browser-dynamic": path.resolve(__dirname, "node_modules/@angular/platform-browser-dynamic")
```

**Comment by danbucholtz** [comment]
Hi @rapropos,

Thanks for sharing!  I'll try it on Tuesday and get back to you!

Thanks,
Dan

**Comment by danbucholtz** [comment]
Hi @rapropos,

It might be a few days.  Really swamped right now!

Thanks!
Dan

**Comment by dorontal** [comment]
Thanks so much for those aliases which will probably solve my problem @rapropos, but I am not sure how to use them.  Where do I put those?

**Comment by danbucholtz** [comment]
Changing assignment to @jthoms1 to ensure this works with forth coming webpack build process.
