### ISSUE TITLE
Livereload flashy

### ISSUE THREAD

**Issue by michaelnatkin** [ionic-team/ionic-cli#114]
Loving the new CLI livereload feature so much. I feel bad even asking about this problem because compared to not having livereload my life just got so much better. But I do notice that when I make a change, the webview reloads maybe 3-5 times in quick succession before settling down. My guess it that my gulp watch is changing several files and livereload is seeing each of them, rather than throttling and waiting to see that no files have changed for at least a second or something?

**Comment by mikehaas763** [comment]
This is currently a problem I'm having. It looks like too many changes are happening to quickly and the ionic server is crashing (even though my gulp watch is still running). In my case, I do not have bundling. I am using System.register modules which is transpiled from ES6 modules. The loader automatically fetches the modules over http as it walks the dependency graph.

Sure, I could make my build process smarter by doing different things such as only outputting to the `www/` directory the actual file that was changed rather than all the JS files when one has changed. It's something I'll likely do anyways to increase build speed. That's not a solution to the underlying problem though, it just hides it.

When I first run `ionic serve` I run a full build and then run a watch. The ionic server crashes right away because while a full build has began and is running the ionic server has concurrently started and sees many changes happening in quick succession. It can also crash if I run my gulp build command manually.

I'm definitely willing to submit a PR with a throttle if it's reasonable. That should fix this issue the majority of the time. Although, it would be nice to only trigger the reload directly from the gulp watch process. Not sure if there are any clean options for interprocess communication though between gulp watch and ionic serve.
