### ISSUE TITLE
'Ionic serve' cant be run as a background process

### ISSUE THREAD

**Issue by TheoAndersen** [ionic-team/ionic-cli#1265]
if i run `ìonic serve&`  (perhaps with a few options for no browser etc.) then i cant `curl`the url thats being hosed from the same shell.

It works if i create two different shells (not in background mode) but not as a background job in the same shell. 

This is easy to recreate - and i've tried in on both Ubuntu 14 and Osx Capitan.

It seems that when running as a background job, that when i press 'enter' to get to the shell promth again, the job dosen't get killed - but it stops being able to respond to web-request for the url hosted.

Is there any solution to this?

I'm trying to setup e2e tests on circleci and this is the last problem i have (i think). ;)

Thanks

**Comment by MartijnW49** [comment]
I ran into the same issue when trying to run e2e tests in a jenkins build.
What I did was run the app using node which does run in the background.

`node server.js &`

The content of my server.js (which is in the root of my ionic 2 project)
```
var connect = require('connect');
var serveStatic = require('serve-static');
connect().use(serveStatic("www")).listen(8100, function(){
    console.log('Server running on 8100...');
});
```

You'll also need to install the following for the script to work
`npm install connect serve-static`

**Comment by thomcom** [comment]
Hey, it looks like the right answer here is simply to use the `nohup` command:

    nohup ionic serve $> ionic.log &

Will run ionic serve in the background, breaking its stdin pipe, and sending all of its output to ionic.log.

**Comment by ntreadway** [comment]
[Example that is working on codeship](https://gist.github.com/ntreadway/7b53a78c6b3096083b6736e2974084a7)

**Comment by excaliburHisSheath** [comment]
I just ran into this issue while trying to setup end-to-end testing on our Jenkins server, and I spent some time trying to understand what was going on.

Here's what I've observed when running `ionic serve` in the background:

```
$ ionic serve -bd &
[1] 10120
$
[1]+  Stopped                 ionic serve -bd
$ ps 10120
  PID   TT  STAT      TIME COMMAND
10120 s000  T      0:00.30 ionic   
$ kill 10120
$ ps 10120
  PID   TT  STAT      TIME COMMAND
10120 s000  T      0:00.30 ionic   
$ kill -9 10120
[1]+  Killed: 9               ionic serve -bd
$ ps 10120
  PID   TT  STAT      TIME COMMAND
```

What I'm observing is that if I use `&` to run `ionic-serve` in the background, it appears to start normally, but the site can't be viewed in a web browser or contacted with `curl`. Once I enter any command into the terminal (even hitting `<Return>` without any command) I'll see a message saying that the process was stopped. However, if I run `top` or `ps` I can see that the process is still active, but it can't be reached through `localhost:8100`. Using `kill` with the PID doesn't seem to kill it (as I would expect), but `kill -9` works.

It seems like there's something odd about how `ionic serve` is setup that's causing it to fail to start properly. If I try sending the output of `ionic serve` to a file by doing `ionic serve > serve.log &`, then I see no log file ever appear. That makes me think that the issue is that the server never even starts when running in the background.

From what I've found, no combination of `nohup` or `screen` seem to fare any better. In particular, I tried the `nohup`-based solution that worked for @thomcom, but it didn't fare any better for me.

---

In order to work around this issue, I expanded on the solution @MartijnW49 posted. Using `serve-static` to just serve the contents of `www` works, so I added the following script to my `package.json` to automate the process fully:

```
"scripts": {
    "e2e": "ionic-app-scripts build; node serve-static.js& npm run e2e:standalone; kill %1",
    "e2e:standalone": "webdriver-manager update --standalone false --gecko false; protractor ./test-config/protractor.conf.js"
}
```

Now running `npm run e2e` will build the current version of the app (so that `www/` is up to date), start the static file server, run my e2e tester, then kill the static server. Doing `node serve-static.js &` seems to have no problems running in the background, which further indicates that there's some issue with how `ionic serve` is working.

---

I'm running on MacOS Sierra with Ionic CLI 3, I can provide full info on the setup for my local machine and our Jenkins server if it'd help diagnose the issue.

**Comment by dwieeb** [comment]
Hey all, I just spent some time fixing this. You should be able to do `ionic start &` in the next release of CLI v3.

**Comment by dbecher-ito** [comment]
@thomcom Thank you! I really was looking for that command, since our requirements don't allow to upgrade to CLI v3.

Would you care to elaborate what `$>` in your command exactly does? I know the usual pipe redirects like `> /dev/null 2<&1` e.g. to redirect stdout and stderr to `/dev/null`. But what is `$>`? Couldn't find something regarding this on the web.

**Comment by dbecher-ito** [comment]
Just noticed that `nohup ionic serve --nobrowser --nolivereload $> ionic.log &` doesn't seem to work after all... :(

**Comment by dwieeb** [comment]
@dbecher-ito You have to use `--no-interactive`:

```
nohup ionic serve --no-interactive --nobrowser --nolivereload $> ionic.log &
```

**Comment by abuanmi** [comment]
So I was configuring a CI on bitbucket pipelines this worked for me:

screen -d -m -L ionic serve --no-open --no-livereload

**Comment by brad** [comment]
I found a very simple hack for this guys:
```
sleep 999999999 | ionic serve -b &
```

**Comment by dwieeb** [comment]
@abuanmi @brad does this not work for you? https://github.com/ionic-team/ionic-cli/issues/1265#issuecomment-315810662

The `--no-interactive` turns it into a CLI for machines, not humans.

**Comment by brad** [comment]
@dwieeb I'm stuck on an old version which apparently predates that flag
```
$ ionic --version
1.7.16
```

**Comment by dwieeb** [comment]
@brad What's stopping you from upgrading? The latest CLI should support all versions of Ionic.

**Comment by brad** [comment]
@dwieeb We will upgrade eventually, but we are trying to get a release out the door and don't want to make any fundamental framework upgrades until after the release to avoid breaking things
