### ISSUE TITLE
error npm install 

### ISSUE THREAD

**Issue by KalaniGanga** [ionic-team/ionic-cli#1357]
when i try to install npm i got this error message 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "restart"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path C:\cygwin64\home\Onbit\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\cygwin64\home\Onbit\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\Onbit\npm-debug.log

can some please fix this soon

**Comment by caleuanhopkins** [comment]
are you trying to install npm or ionic through npm? You may be better off installing node to run in powershell or command prompt rather than cygwin. You can checkout the treehouse guide here: [http://blog.teamtreehouse.com/install-node-js-npm-windows](http://blog.teamtreehouse.com/install-node-js-npm-windows)
