### ISSUE TITLE
'ionic docs' in CLI (v2) brings you to the old documentation

### ISSUE THREAD

**Issue by PeterKassenaar** [ionic-team/ionic-cli#1457]
I typed `ionic docs` in the terminal to read documentation on how to start a new project.

In the browser the V1 documentation is opened, instead of V2 documentation (subsequently I made a lot of errors generating a new project ;)

**Comment by jthoms1** [comment]
If you execute this command within a v2 project folder it should provide you with the correct documentation, but it appears this is a bug right now. 

If you execute the command outside of a v2 project folder it will provide v1 documentation which is correct.  We would like to keep it this way because v2 is still not offically released as final.

Thanks for reporting this!

**Comment by juarezpaf** [comment]
I was about to report this issue. I know it's not that easy to support both Ionic versions, but it'll be great to have `ionic docs ls` to show the list of options available for an Ionic 2 project.
Currently running workshops in Brazil's Northeast and I'm including as many example of Ionic CLI as possible. 
If I type `ionic docs component cards` and get the browser open into https://ionicframework.com/docs/v2/components/#cards will be A.M.A.Z.I.N.G.
Keep rocking @jthoms1 🙌
