### ISSUE TITLE
Revisit Generators

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/ionic-cli#1731]
- [ ] Provide friendly output text on success and fail

- [ ] Add newly created thing to `NgModule`

- [ ] Investigate leaving prompt stuff in CLI and moving the logic of creating stuff to app-scripts. Leave templates in ionic-angular

Thanks,
Dan

**Comment by brandyscarney** [comment]
Also it would be nice if it checked if the page existed already. If I add a page that already exists it adds the new directory and overrides the old one. :)

**Comment by danbucholtz** [comment]
Good idea Brandy, should be easy enough to do.

**Comment by brianlittmann** [comment]
I'm just gonna piggy-back on this issue and see what you all think about adding support for generating directory based pages/components. That is, if I run `ionic g page compete/results`, it'd be rad to have it create the `pages/compete` directory if it doesn't already exist, then create the `results` page inside that dir.

Certainly just a nicety and probably not a priority, but that's the structure I'm currently using to keep things fairly organized since feature modules within Ionic don't seem officially supported yet.

**Comment by DrakeWitt** [comment]
If the generator had the ability to automatically inject the new page or provider into the ngModules that  would be immensely helpful.

**Comment by dwieeb** [comment]
Might go without saying, but for CLI 4 and Ionic 4 we're using Angular schematics, so I'm closing this issue.
