### ISSUE TITLE
v3: Fully documented `ionic build` command?

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2206]
Right now one can run `ionic serve` or `npm run build` (undocumented) to get a simple build from `/src` to `/www`. From what I understand, `/www` is expected to be used if one wants to create a PWA or webserver hosted version of an Ionic app - which more and more people tend to do.

Wouldn't it be great, now that `ionic build` is not hijacked by `ionic cordova build` any more, to add and fully document this command to the CLI?

**Comment by dwieeb** [comment]
Too early yet. Right now people will update to CLI v3 and type `ionic build` expecting a Cordova build. Our goal with this first release is to release the stranglehold of the Cordova commands in our CLI so that `ionic build` can mean something else later. We're basically squatting on our own command name. We haven't changed the build process. `npm run build` is still a thing for simple builds, and `ionic build` is now `ionic cordova build` (which does a simple build beforehand).

**Comment by piotrowski** [comment]
Ok, makes sense.
