### ISSUE TITLE
Hooks not getting parent's command parameters

### ISSUE THREAD

**Issue by lordgreg** [ionic-team/ionic-cli#2463]
**Description:**
1. Run `ionic serve --nobrowser --test=123 --foo bar`.
2. Have `"ionic:watch:before": "node ./changeEnvironment.js",` script in `package.json`.
3. Await the same parameters passed to serve command also be available in hook.

**Steps to Reproduce:**
Same as description.

**Output:**
```
{ _: 
   [ '/usr/local/Cellar/node/7.7.4/bin/node',
     '/Users/AAA/Projects/BBB/changeEnvironment.js' ] }
```

Should be:
```
{ _: 
   [ '/usr/local/Cellar/node/7.7.4/bin/node',
     '/Users/AAA/Projects/BBB/changeEnvironment.js' ],
  test: 123,
  foo: 'bar' }
```

**My `ionic info`:**
```
▶ ionic info

global packages:

    @ionic/cli-utils : 1.4.0-alpha.e838a5d7
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0-alpha.e838a5d7

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v7.7.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 5.0.3 

```

**Comment by dwieeb** [comment]
There are numerous places those arguments could go. (app-scripts to build the app? the express server that runs livereload? `ionic:watch:before` vs `ionic:watch:after`?) 

What happens if someone uses `"ionic:watch:before": "node ./myScript.js --test=123"` and runs `ionic serve --test=abc`?

The cordova run/emulate command muddles this even more by introducing cordova args _and_ dependent cordova-ios args, xcode build args. 

I think a better solution would be to have a real hook system where the CLI calls a function in your script with various parameters. What that actually looks like is to-be-determined.

**Comment by lordgreg** [comment]
I think that all cli hooks provided should forward the params to their respective child calls. 

Your example is showing a conflict, of course. But, at the moment, there's no solution for parametrisation at all. The simplest, for ionic cli developers is easily to forward the params given to parent. It is up to you in child process on how to use them or how to deal with conflicts.

**Comment by dwieeb** [comment]
@lordgreg There's no solution yet because if I put your solution in, I'd have to maintain it and deal with all the broken edge cases (might be more unforeseen ones I haven't thought of, as well) until CLI version 4. 

I'm sorry this feature is missing, but it's not a commonly requested feature, and the hook system itself is brand new. Give me time to work on a solution that isn't a nightmare.

**Comment by lordgreg** [comment]
thank you for your feedback @dwieeb. I wish you all the best developing the cli 👍

**Comment by dwieeb** [comment]
@lordgreg In your `changeEnvironment.js` script, what exactly are you hoping gets passed along? Just any parameters to `ionic serve`? What else would be helpful? What is your use case? 

Please comment in my new issue: https://github.com/ionic-team/ionic-cli/issues/2594
