### ISSUE TITLE
Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of date.

### ISSUE THREAD

**Issue by mzl1988** [ionic-team/ionic-cli#2514]
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.1
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

 Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of
       date.
TypeError: Cannot read property 'forEach' of undefined

**Comment by jimiatworking** [comment]
I got the same issue.

**Comment by adadgio** [comment]
Everyone has.

See also other issues with more/less descriptions : https://github.com/ionic-team/ionic-cli/issues/2516

https://github.com/ionic-team/ionic-cli/issues/2512

**Comment by Justinzhq** [comment]
`npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest`

**Comment by adadgio** [comment]
Nope, did that, not working; Shouldnt be closed.

**Comment by dwieeb** [comment]
@adadgio It's closed because in no way is this the fault of the Ionic CLI. Node/npm environments get screwy sometimes because the development is going at 150mph. Whenever you get obscure issues, try using the variety of tools at your disposal.

`npm outdated` - shows you which packages are out of date
`rm -rf node_modules; rm package-lock.json; npm install` - start fresh from your package.json definitions
try different versions of node _and_ npm to debug

Your issue isn't even related to the original issue. They're different errors entirely. If @mzl1988 could run the command with `--verbose`, I could see where the error is coming from.

**Comment by suchi2207** [comment]
I also got the same issue/error (@ionic/cli-plugin-cordova) last few days,  found issue in the code and fixed. please try to find the issue in your code side as well if any or any help required please reach me pavan2106@gmail.com

**Comment by Devashish09** [comment]
@Justinzhq , this solution is not working in my case.

**Comment by dwieeb** [comment]
@Devashish09 This issue is very old. The CLI does not use this plugin anymore. Please uninstall all CLI plugins you see in `package.json` (except the proxy plugin, if you're using it). Then, make sure you have the latest CLI installed: `npm i -g ionic@latest`. Make sure you don't have it installed locally: `npm uninstall ionic`.

If you have an issue, please create a new issue and fill out the issue template.
