### ISSUE TITLE
changelog isn't updated

### ISSUE THREAD

**Issue by MohammadWaleed** [ionic-team/ionic-cli#2515]
changelog file doesn't contain the latest changes for version 3.5.0

https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md

**Comment by dwieeb** [comment]
@MohammadWaleed Haha, it was on my todo list today. We use lerna which does update the changelogs of each package (https://github.com/ionic-team/ionic-cli/tree/master/packages), but I like to write some manual stuff up, because lerna just uses the commit messages, which aren't always informative to users.
