### ISSUE TITLE
livereload ip address - need to specify every time

### ISSUE THREAD

**Issue by shawnlan** [ionic-team/ionic-cli#2541]
When multiple network interfaces detected, I am prompted to select an IP address. Or I can use the `--address` option. Either way, this needs to be done every time I run `ionic cordova run --livereload`. I remember in previous versions I would just need to do it once. It was much more convenient. Should do the same in the current version, or at least a config file where I save the IP address.

**Comment by dwieeb** [comment]
It could be a config option, for sure

**Comment by dwieeb** [comment]
@shawnlan Going to have to wait on this still. I thought we could put it in `ionic.config.json`, but that's a file that is committed and shared across team members, and this would just be a configuration option for one's local computer. I have to think about where to store it.

**Comment by shawnlan** [comment]
Maybe an env variable that the cli can read from?

**Comment by dwieeb** [comment]
Yeah, that's what I was thinking. But since `--address` is just an option, I could do this in a reusable way that would enable all command line flags to be environment variables.

For example, the command `ionic cordova run ios -lc --address=localhost` could also be:

```
export IONIC_CMDOPTS_CORDOVA_RUN_LIVERELOAD=1
export IONIC_CMDOPTS_CORDOVA_RUN_CONSOLELOGS=1
export IONIC_CMDOPTS_CORDOVA_RUN_ADDRESS=localhost
ionic cordova run ios
```

The environment variables would be predictably named and would work for all CLI command options.

**Comment by shawnlan** [comment]
I think that's a good idea.

**Comment by dwieeb** [comment]
@shawnlan 3.15.0 is out with this change!

**Comment by shawnwithlegion** [comment]
Thank you!!
