### ISSUE TITLE
[ERROR] Unable to find command: state restore

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-cli#2611]
_From @mluis on August 4, 2017 11:37_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
$ ionic state restore
[ERROR] Unable to find command: state restore
*snip*
$

**Expected behavior:**
$ ionic state restore
The most similar command is
    <command here>
$

**Steps to reproduce:**
$ ionic state restore

**Related code:**

**Other information:**
Not easy to find documentation.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
[ERROR] Error with www/lib/ionic/version.json file:
        FILE_NOT_FOUND

cli packages: (node_modules)

    @ionic/cli-plugin-cordova : 1.6.2
    @ionic/cli-plugin-gulp    : 1.1.1
    @ionic/cli-plugin-ionic1  : 2.1.1
    @ionic/cli-utils          : 1.7.0
    ionic (Ionic CLI)         : 3.7.0

global packages:

    Cordova CLI : 7.0.1 
    Gulp CLI    : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : ios 4.4.0
    Ionic Framework   : unknown

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 3.10.9 
```

_Copied from original issue: ionic-team/ionic#12579_

**Comment by dwieeb** [comment]
@mluis I assume you recently upgraded from CLI v2. Please review the changelog for documentation on CLI changes: https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2

**Comment by dwieeb** [comment]
@mluis CLI v3 should work great for Ionic 1 projects. Let me know if you encounter any issues.

**Comment by mluis** [comment]
@dwieeb the issue was when adding platforms and plugins based on the package.json legacy format.

Memory notes: had to install python's six module by hand, cordovaPlugins and cordovaPlatforms weren't translated to the new package.json object { ... : ..., cordova: { platforms: [], plugins: [] } }.

I adapted 2 scripts found online in order to help me.
You might find them attached here.
[platforms.js.txt](https://github.com/ionic-team/ionic-cli/files/1201340/platforms.js.txt)
[plugins.js.txt](https://github.com/ionic-team/ionic-cli/files/1201341/plugins.js.txt)

ionic-cli performed as expected upon package.json after that.

**Comment by dwieeb** [comment]
@mluis `cordovaPlugins` and `cordovaPlatforms` were `ionic state` properties. The `cordova` object is Cordova's properties. That's why it wasn't automatically migrated.

**Comment by mluis** [comment]
@dwieeb yup!

**Comment by dwieeb** [comment]
@mluis Ah, okay. There are quite a few things CLI v3 does to make sure older projects are modernized. I purposefully left out the `cordovaPlugins`/`cordovaPlatforms` because I figured it would be a good idea for people to manually migrate to learn the [new way Cordova handles this](https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/). Let me know if something else is amiss. I am committed to ensuring older Ionic projects are easily "imported" into the new CLI experience.

**Comment by mluis** [comment]
@dwieeb yes, I wouldn't also. I'm wondering if keeping cordovaPlugins/cordovaPlatforms turns package.json backward compatible with ionic-cli v1 perhaps?
