### ISSUE TITLE
3.6+: global CLI version not relevant any more?

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2615]
Since 3.6 the global CLI version doesn't seem to be reported by `ionic info` any more. This is a problem, because some people accidentally run `ionic info` outside of their project. It would be nice to see the global CLI version here anyway.

Example: https://forum.ionicframework.com/t/ionic-builds-apk-for-hours/100605

**Comment by dwieeb** [comment]
It is not relevant. This has always been the case for CLI v3. If they run `ionic info` in the project, they get more info like locally installed Ionic framework and Angular versions, Cordova platforms, etc. We just need to ask them to run it in their project. There's also a warning if ran outside of the project directory.

**Comment by janpio** [comment]
Does it matter what version is installed globally? Should the versions match?

**Comment by dwieeb** [comment]
The global version should also be kept up to date for `ionic start`, etc. Ideally they should match because they should be up to date, always. But they no longer need to match exactly because the global `ionic` binary diverts execution to the locally installed version almost in entirety.

See https://github.com/ionic-team/ionic-cli/blob/master/packages/ionic/bin/ionic and https://github.com/ionic-team/ionic-cli/blob/master/packages/cli-utils/src/bootstrap.ts

**Comment by janpio** [comment]
How do other CLIs that work similar handle these version mismatched?
Does the update logic also cover the global CLI or only the local one?

**Comment by akaplo** [comment]
"Not relevant anymore" does **not** mean that we don't still need the global version of the CLI installed, correct? 

All the talk of a "local CLI" install has [confused my team](https://github.com/umts/pvta-multiplatform/issues/378) into thinking we could uninstall the global CLI and simply use the local one without needing to add an `npm run ionic` script to our `package.json`.

**Comment by janpio** [comment]
afaik the global install is the only way to have `ionic` as a command.

**Comment by dwieeb** [comment]
@akaplo The _version_ of the global CLI is not relevant when using `ionic info` _locally_. I thought that's what this issue was asking.

The global CLI is certainly relevant if you wish to use `ionic start` or any command that does not need project context. But as soon as you're in a local project, the `ionic` binary just uses the local CLI. This is how gulp and other common CLIs on Node work. They do this because it's generally bad to mix `node_modules` folders when requiring CLI plugins. (Indeed we saw quite a few JS runtime errors because of this.)

This behavior may change, as I hope to actually move the CLI plugins back into the main `ionic` package and redo how the plugins work, at which point the local version may not need to be installed anymore. The CLI plugins have caused quite a few headaches, so I'm trying to take small steps to ease the pain.

**Comment by akaplo** [comment]
Thanks @janpio and @dwieeb!  This make infinitely more sense to me.  @dwieeb you're right about the original scope of this issue; I see that now.  Sorry for hijacking!

**Comment by dwieeb** [comment]
@akaplo No worries 😄 The CLI (in fact the entire Ionic dev toolkit) is going through a confusing time right now. I am confident we come out the other end with solutions that make sense and work great.
