### ISSUE TITLE
Feature request: Add capability to generate modals using `ionic generate`

### ISSUE THREAD

**Issue by chandanch** [ionic-team/ionic-cli#2683]
Currently the CLI provides the capability to automatically generate pages, _pipes, directives, providers, components_ using the `ionic generate <type> <name>` .  

If we have to create a **modal** in our app then we have to manually create the `modal.html`,  `modal.ts`  & `modal.scss` files. 
Along with this we will have to create the appropriate template and add import all the necessary classes. 

Instead, we could generate the modal automatically using the `ionic generate` like this:
`ionic generate modal signup`
 This will automatically create .html, .scss and .ts file. 

**Note**:  All the modals can be created in `modals` folder. For example `src/modals/signup`

**Comment by Tharindu-Diluksha** [comment]
This is a valuable feature to be included in ionic CLI. I would appreciate the effort of opening an issue.

**Comment by mhartington** [comment]
Hi! So Im not 100% sure I see the benefit of adding this. Since any `@Component` can be loaded in a modal, there's really no need to create an extra generator for a modal. 

As for the modal folder, this kind of go against the logic we had for our navigation. Since any component can be loaded component as a modal, adding a specific modals directory seems, unnecessary.

Unless there's something I'm not seeing or missing, which could be the case 😄 , I don't think we need to add this.

**Comment by chandanch** [comment]
Hi, @mhartington yes, you are right, any component can be loaded as a modal henceforth we don't need a separate generator. Adding a component in a specific folder can be user preference, for example _Signup Modal_, _LoginModal _ can go under the modals folder. Since any component can be loaded as a modal we may not this as well.

**Comment by mhartington** [comment]
We might add the ability for that at a later point, custom folders/paths, but for now, it's not a priority
