### ISSUE TITLE
Feature request: Custom Select Interfaces

### ISSUE THREAD

**Issue by DavidTalamona** [ionic-team/ionic-cli#2697]
Selects can have three types of interfaces, all limited in number of items by the screen size.

I would like to see the interface types to be classes with some sort of registration process like with the Menu where one could create and register a custom type implemenation via MenuController.registerType('XXX', XXX);.

This would allow me to create interfaces like opening a new page with a virtual list in it and unlimited items, a search field to filter those items and some custom ok / cancel buttons.

This custom interfce class would have to implement a method to pass the selected item(s) back to the Select.
It would then be necessary to make the ion-options optional because this (possibliy big) number of items should not be written to the DOM.

**Comment by DavidTalamona** [comment]
Sorry, opened this issue in `/ionic-cli` - could someone please move it to `/ionic`?
THX!

**Comment by kensodemann** [comment]
Hello! Thank you for the feature request. 

Rather than moving this to `ionic-team/ionic` I am going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to `ionic-team/ionic` when we have begun implementation.

Thanks!

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-feature-requests#303
