### ISSUE TITLE
ionic Cordova build iOS error 

### ISSUE THREAD

**Issue by Loveying** [ionic-team/ionic-cli#2797]
ionic Cordova build iOS ,when I run project to Phone ,the app can't connect net ,why?

**Comment by navi8602** [comment]
I ask for help! All projects stopped compiling, everything hangs at the start and in the console Xcode 
gives an error and the application does not load further


`2017-10-11 10:34:22.678412+0300 PetMDHealth[644:541289] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///private/var/mobile/Containers/Data/Application/2D5C2587-7A03-4388-8A6B-D2A962C9AD92/Library/Cookies/Cookies.binarycookies
2017-10-11 10:34:22.781159+0300 PetMDHealth[644:541289] Apache Cordova native platform version 4.5.0 is starting.
2017-10-11 10:34:22.782461+0300 PetMDHealth[644:541289] Multi-tasking -> Device: YES, App: YES
2017-10-11 10:34:22.798221+0300 PetMDHealth[644:541289] -[__NSDictionaryM cordovaSettingForKey:]: unrecognized selector sent to instance 0x174048cd0
2017-10-11 10:34:22.799557+0300 PetMDHealth[644:541289] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM cordovaSettingForKey:]: unrecognized selector sent to instance 0x174048cd0'
*** First throw call stack:
(0x18a582fe0 0x188fe4538 0x18a589ef4 0x18a586f54 0x18a482d4c 0x100124ec4 0x100072504 0x1906b4b04 0x1906b46e0 0x1906baf60 0x1906b83fc 0x190729e68 0x10012969c 0x100072220 0x190725e48 0x19093237c 0x190937e24 0x19094c8b0 0x1909350b8 0x18c12c884 0x18c12c6f0 0x18c12caa0 0x18a53142c 0x18a530d9c 0x18a52e9a8 0x18a45eda4 0x19071efc8 0x190719c9c 0x100072110 0x18946d59c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by dwieeb** [comment]
@navi8602 Please don't hijack issues. Create a new issue and fill out the issue template. From glancing at that error you're more likely to find a solution by asking in the [Ionic Forum](https://forum.ionicframework.com/) or Stack Overflow. It's probably some Cordova plugin that's causing your issue, and without knowing more about your project, I won't be able to help. 

@Loveying Please fill out the issue template. I'm going to need a _lot_ more information to be able to help you.

**Comment by LuizTokuhara** [comment]
@Loveying
Maybe if you are using the WKWebView you need to enforce CORS or install the HTTP plugin.
http://blog.ionic.io/wkwebview-for-all-a-new-webview-for-ionic/
