### ISSUE TITLE
Monitoring syncmaps command cannot be scripted

### ISSUE THREAD

**Issue by codinronan** [ionic-team/ionic-cli#2808]
**Description:**
Hi there! I'm surprised nobody has brought this up before, but it's a scenario I am looking at so I wanted to ask if there is interest:

Essentially I want to script my build process, including the building & syncing of my sourcemaps via the `ionic monitoring syncmaps` command. Currently, there is no code path that avoids being prompted to make a decision, which effectively makes it impossible to script the syncmap uploading as part of the build.

I looked at the syncmaps command source and it should be pretty easy to implement a command line flag to simply go straight through:

https://github.com/ionic-team/ionic-cli/blob/master/packages/ionic/src/commands/monitoring/syncmaps.ts

I am happy to produce a PR with this feature, if there is interest? I know the docs say that there is work in progress to make it easier to automate that part of the process so maybe I'm way off. 

Effectively, a command like: 

* `ionic monitoring syncmaps --no-interactive` would just use whatever is already there, or invoke the prod build if there are none;
* `ionic monitoring syncmaps --no-interactive --prod` would force a prod build.

In each case the existing sourcemap directory would be respected, that is, you must provide the `--prod` argument in order to generate new ones; otherwise they would be uploaded as-is.

Thoughts?

**Comment by dwieeb** [comment]
Hi @codinronan! Thanks for submitting the issue. We understand the limitations of `ionic monitoring syncmaps` and intend to improve upon the workflow within the next few weeks.

That being said, could you possibly do `CI=1 ionic build --prod && ionic monitoring syncmaps` in your build process?

**Comment by timbru31** [comment]
I'm hijacking this issue since my problem is related to the missing flexible configuration of the source maps syncing.
The docs (https://ionicframework.com/docs/pro/monitoring/) state that:
> APP_VERSION is the version of the code running for the purposes of tracking code changes. We strongly recommend that this mirrors the version in package.json or config.xml.

However I've noticed that the package.json version does not matter at all, since there is a hardcoded check of the Cordova/config.xml version (see https://github.com/ionic-team/ionic-cli/blob/master/packages/ionic/src/commands/monitoring/syncmaps.ts#L36).

I'd like to have this configurable, too, since we use the package.json version as the semver one and like to upload the sourcemaps with this version instead.

**Comment by timbru31** [comment]
For anyone looking how to sync the sourcemaps with the package.json version here are two commands that work in the CI (e.g. GitLab CI)
```bash
PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
sed -i -e "s/version=\"[0-9]*\.[0-9]*\.[0-9]*\"/version=\"$PACKAGE_VERSION\"/g" config.xml
```
This uses Node.js to read the current package.json version and replaces the config.xml version via sed.

**Comment by dwieeb** [comment]
@codinronan Please test the latest alpha CLI: `npm i -g ionic@canary`. I've switched up how this command operates to be more in line with how you described. (I used `--build` for the flag name, not `--prod`, but functionally it's the same as what you outlined.) Please let me know how you like it. Apologies for the delay in taking a look into this.

@timbru31 Yeah, I'm guessing Ionic Pro is using the `config.xml` version because the Pro client uses that info from the `cordova-plugin-ionic`. I'll be honest, the UX for Ionic Monitoring is not the best right now. The Pro team is prioritizing the work they do, but Monitoring is lacking behind the other Pro services.
