### ISSUE TITLE
ionic serve doesnt work in visual studio after updating 3.15.1

### ISSUE THREAD

**Issue by theonuryildiz** [ionic-team/ionic-cli#2839]
I had a working solution a few hours ago (it was 3.x something).

Then i updated it to ionic 3.15.1 to add native plugins to my project. I updated everything but when i use NPM TASK RUNNER from visual studio i got:
Failed to load resource: the server responded with a status of 404 (Not Found) (main.css)
Failed to load resource: the server responded with a status of 404 (Not Found) (main.js)
Failed to load resource: the server responded with a status of 404 (Not Found) (vendor.js).

When i get in the directory with cmd and run ionic serve it works fine.

What am i missing? What am i doing wrong?

My package.json file looks like this:

> {
>   "name": "io.cordova.myappae06db",
>   "author": "",
>   "homepage": "",
>   "private": true,
>   "scripts": {
>     "clean": "ionic-app-scripts clean",
>     "build": "ionic-app-scripts build",
>     "ionic:build": "ionic-app-scripts build",
>     "ionic:serve": "ionic-app-scripts serve",
>     "watch": "ionic-app-scripts watch"
>   },
>   "dependencies": {
>     "@ angular/common": "4.4.3",
>     "@ angular/compiler": "4.4.3",
>     "@ angular/compiler-cli": "4.4.3",
>     "@ angular/core": "4.4.3",
>     "@ angular/forms": "4.4.3",
>     "@ angular/http": "4.4.3",
>     "@ angular/platform-browser": "4.4.3",
>     "@ angular/platform-browser-dynamic": "4.4.3",
>     "@ ionic-native/core": "4.3.2",
>     "@ ionic-native/splash-screen": "4.3.2",
>     "@ ionic-native/status-bar": "4.3.2",
>     "@ ionic/storage": "2.0.1",
>     "@ types/jquery": "^3.2.13",
>     "cordova-android": "^5.2.1",
>     "ionic-angular": "3.7.1",
>     "ionic-app-lib": "^2.2.1",
>     "ionicons": "3.0.0",
>     "jquery": "^3.2.1",
>     "rxjs": "5.4.3",
>     "sw-toolbox": "3.6.0",
>     "zone.js": "0.8.18"
>   },
>   "devDependencies": {
>     "@ionic/app-scripts": "^3.0.1",
>     "@types/jquery": "^3.2.13",
>     "typescript": "2.3.4"
>   },
>   "description": "Ionic2Tabs: An Ionic project",
>   "cordovaPlugins": [
>     "cordova-plugin-whitelist",
>     "cordova-plugin-console",
>     "cordova-plugin-statusbar",
>     "cordova-plugin-device",
>     "cordova-plugin-splashscreen",
>     "ionic-plugin-keyboard"
>   ],
>   "cordovaPlatforms": [],
>   "-vs-binding": {
>     "BeforeBuild": [
>       "ionic:build"
>     ],
>     "ProjectOpened": [
>       "watch"
>     ]
>   },
>   "cordova": {
>     "plugins": {
>       "cordova-plugin-console": {},
>       "cordova-plugin-device": {},
>       "cordova-plugin-splashscreen": {},
>       "cordova-plugin-statusbar": {},
>       "cordova-plugin-whitelist": {},
>       "ionic-plugin-keyboard": {}
>     },
>     "platforms": [
>       "ios"
>     ]
>   }
> }

**Comment by Notifium** [comment]
Hi,
I'm getting similar issues across two different development PCs. Did you find a fix?
Andy

**Comment by theonuryildiz** [comment]
Re-installing visual studio worked once i guess. 
Im using console since then.

**Comment by ManojJangra** [comment]
Hi,
Same issue
Refused to apply style from 'http://localhost:8100/build/main.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
vendor.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Refused to execute script from 'http://localhost:8100/build/vendor.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
main.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Refused to execute script from 'http://localhost:8100/build/main.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to apply style from 'http://localhost:8100/build/main.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by ManojJangra** [comment]
pls suggest me for the same.
