### ISSUE TITLE
ionic serve says okay but not working ! ==?

### ISSUE THREAD

**Issue by Ejdersoy** [ionic-team/ionic-cli#2879]
<img width="567" alt="ekran alintisi" src="https://user-images.githubusercontent.com/20680870/32769097-ceb22036-c8ad-11e7-8dea-bc398d72842b.PNG">
<img width="670" alt="ekran alintisi" src="https://user-images.githubusercontent.com/20680870/32768587-bff1b3c4-c8ab-11e7-9162-02d42aabdfe4.PNG">
as you can see it says okay but not working.  please help me . my ionic CLI 3.18.0 and npm and everyting is lastest version. but its not working .  

and ı am not using daemon something. ı just want to when ı am write ionic serve its open my project. but for now its now working be hurry . please !

**Comment by dwieeb** [comment]
@Ejdersoy Are you using git bash?

**Comment by Ejdersoy** [comment]
@dwieeb no ı am not. node js.

**Comment by dwieeb** [comment]
@Ejdersoy I meant what terminal are you using? `cmd.exe`? git bash? hyper terminal?

**Comment by Ejdersoy** [comment]
@dwieeb ı am using cmd.exe

**Comment by atomicnation** [comment]
Same happens to me. At the moment i'm able to work by executing `npm run ionic:serve` instead. @dwieeb youcould try it meanwhile.

![image](https://user-images.githubusercontent.com/567868/34114395-fa7ebe92-e412-11e7-879d-7f1a3f698bba.png)

![image](https://user-images.githubusercontent.com/567868/34114453-1ff44782-e413-11e7-8526-7d2413594d83.png)

Any ideas?

**Comment by dwieeb** [comment]
No ideas immediately... it just seems to be outright failing silently on Windows.

After running `ionic serve`, can you run `echo %errorlevel%` and tell me what number it is?

**Comment by ParagPallav** [comment]
Hi dwieeb when i use to run  this command echo %errorlevel% it gives me 1 as output.
![image](https://user-images.githubusercontent.com/19725745/34757446-3cb93404-f5f7-11e7-84e7-376aa9623d32.png)
****

**Comment by dwieeb** [comment]
@ParagPallav @gregduffield Do you see this behavior on other terminals, such as Git Bash or hyper? What about other NodeJS versions?

**Comment by gregduffield** [comment]
I have now tried various other versions of node but see the same thing.
I have tried powershell, cmd and the same thing.
I have not tried Bash as I am not willing to change my command toolset for somehting that should work. I am paying for a Pro license at the moment, but it looks like we will not be progressing as we are not able to get past this issue.

I will of course provide any help/information that I can to address this issue, as it would have been good to be able to use the Ionic Framework as designed.

**Comment by dwieeb** [comment]
@gregduffield I understand. I'm not asking you to change your toolset, I'm trying to narrow down the issue so I can address it. I've asked several coworkers and they're not able to reproduce the issue either. Thank you for trying different ideas with me while we debug this. 

Can you try `ionic serve --local`? This should bind the servers to localhost instead of all network interfaces. Are you connected to a network that might kill the connections? Firewall, etc?

**Comment by gregduffield** [comment]
I have tried the -local option and this made no difference. 
I have tried turning off the windows firewall and this made no difference ( there are no other firewalls running)
basically the same thing happens,, we get the OK message then the local, external and DevApp urls and then get shown the prompt. I can see that this works momentarily because if I am running the DevApp My Application gets listed very briefly. for some reason the dev server process is just quitting instead of continuing to run.

**Comment by dwieeb** [comment]
`--local` will also disable the DevApp, so it doesn't appear to be anything related to the multicast code.

Can I have you try `ionic@canary`? In this alpha-version CLI, I have changed how `ionic serve` works, shelling out to `@ionic/app-scripts` instead of importing and running it. I just want to see if that will fix it for you. If it does, I will backport the code to CLI v3, because CLI v4 has not gone through any beta testing.

Install CLI v4 canary:
```
npm uninstall -g ionic
npm install -g ionic@canary
```

Back to CLI v3:
```
npm uninstall -g ionic
npm install -g ionic@latest
```

**Comment by gregduffield** [comment]
Ok i have just tried this and updated to canary 
```
@ionic/cli-utils  : 2.0.0-alpha.273c8f1c
   ionic (Ionic CLI) : 4.0.0-alpha.273c8f1c
```
but sorry to say the same thing still happens. Starts and stops

**Comment by dwieeb** [comment]
Yet `npm run ionic:serve` works? 

Do you have Cordova setup? If so, can you also try `ionic cordova run android -l`?

**Comment by gregduffield** [comment]
SOLVED....

In order to solve the error with cordova trying to get the android platform, I stumbled a related issue to do with adding plugins. The solution is add `c:\windows\system32` to the ` PATH ` environment variables.

Thanks for sticking with me on this, we got there in the end.

**Comment by ParagPallav** [comment]
@dwieeb @gregduffield  npm run ionic:serve this command worked for me . and i am able to run  my app in my local.
Thanks

**Comment by dwieeb** [comment]
@gregduffield I'm confused.. is `ionic serve` working for you now?

**Comment by gregduffield** [comment]
@dwieeb  yes. after updating the path environment variable `ionic serve` is working for me thanks

**Comment by jonathanwerle** [comment]
@dwieeb thanks! I can confirm: this works for me, too.

**Comment by shayanshakil** [comment]
@gregduffield  Thank you for the solution. I was facing the same issue, adding windows/system32 in environment variable resolved the issue.

**Comment by EddieTheOG** [comment]
@gregduffield Also worked for me! Thanks!!!
