### ISSUE TITLE
Wrong information has been given on CLI

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-cli#2898]
**BUG**

> WARN] No write permissions for global node_modules--automatic CLI updates are disabled.
> 
>        To fix, see https://docs.npmjs.com/getting-started/fixing-npm-permissions
> 
>        Or, install the CLI update manually:
> 
>        npm install -g ionic@latest

When I run my app on remote MAC server where I don't have enough permissions it shows above error.This error gives wrong information on 3rd line: `npm install -g ionic@latest`. How can I run that CLI if I don't have permissions? It should be `npm install ionic@latest`. Hope you'll fix this error.

**Comment by dwieeb** [comment]
It should not be `npm install ionic@latest`, as that would install a local version, which may not be what the user wants. The instructions are not incorrect. They are meant as guidance as how to update a global installation, because if this warning is shown, the CLI doesn't know how it _should_ be updated. It's dependent on the system and what the user wants.

For example, for mac & linux this issue can be resolved with using `sudo` if you're on your own laptop. For your remote Mac server, you may need to contact your administrator to have him or her update it. Windows users may need to run a shell as administrator in order to solve it.

Knowing this, what should the message be updated to? Something like:

> [WARN] No write permissions for global node_modules--automatic CLI updates are disabled.
>
> This means you don't currently have access to install or update global packages. For Windows, try running `npm install -g ionic` in a command prompt as an administrator. For Mac and Linux, try running `sudo npm install -g ionic`.
>
> Alternatively, you can fix the permissions of your global package directories for your user by following this guide for npm\[1\] or by installing Node Version Manager\[2\].
>
> \[1\]: https://docs.npmjs.com/getting-started/fixing-npm-permissions
> \[2\]: https://github.com/creationix/nvm

What do you think, @Sampath-Lokuge?

**Comment by Sampath-Lokuge** [comment]
Hi @dwieeb 

Still, you didn't mention anything about `npm install ionic@latest`. Which is very BAD. I have rent a MAC machine and I just need to build `IPA`. That is it. If I'll request to have permission maybe they'll charge more for me and also take a long time to give feedback. But I just run `npm install ionic@latest`  and gave IPA to my tester. But due to it has not been mentioned in the Warning it took time to find out the solution for me. If you'll mention that too on that list then it'll really help for the none mac users. Thanks.

**Comment by dwieeb** [comment]
@Sampath-Lokuge That's because `npm install ionic@latest` is not the right solution for all users, as I explained.

The true issue in this case is that the ownership or permissions of the installation directory is _wrong_. It will always take time to find the solution to this problem because it's not an issue we can automatically fix and we don't want to assume intent.
