### ISSUE TITLE
npm install fails while creating new application with CLI because of node-sass v4.5.3

### ISSUE THREAD

**Issue by ayush987goyal** [ionic-team/ionic-cli#2957]
**Description:**

The url for binding.node file does not exist. Updating the nde-sass dependency to v4.7.2 might fix it.

**Steps to Reproduce:**

1. ionic start my-app
2. error in npm install

**Output:**

Small snippet of output

> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":
HTTP error 404 Not Found

**My `ionic info`:**

CLI: 3.19.0

**Other Information:**

System:

    Node : v9.3.0
    npm  : 5.6.0
    OS   : Windows 10

**Comment by maninak** [comment]
**Work-around steps:**

1. `sudo npm i -g n` install the handy [`n`](https://www.npmjs.com/package/n) tool to switch between node versions

2. `n 8.5.0`

3. PROFIT!! (for me at least, npm installs)

**Details:**

Had the same issue here. It's a huge bummer especially because I encountered it when showcasing a brand new dev to Ionic.

Downgrading to node v8.5.0 (using the handy `[n](https://www.npmjs.com/package/n)` tool) seems to fix it.

Noticed that after downgrading node's version, the binary getting requested is `https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-57_binding.node` (instead of **`linux-x64-59`** which was giving an `HTTP 404` to the caller file `scripts/install.js`).

Previous node version was `v9.4.0`.

Hope this helps @mhartington and anyone else coming from Google.

**Comment by ayush987goyal** [comment]
**Fix from Ionic Team**
Run this command in your project after creation
```bash
npm i @ionic/app-scripts@nightly
```
Should fix the node-sass issue. They are planning to patch this bug where this version of node-sass is not supported in the mentioned node version.

**Comment by mhartington** [comment]
3.1.8 is out!
