### ISSUE TITLE
Android Compile Errors

### ISSUE THREAD

**Issue by BLX-S** [ionic-team/ionic-cli#3053]
**Description:**
I can't compile to Android from the Ionic Cli

**Steps to Reproduce:**
So I installed Gradle separately via Homebrew (macOS) and also have Android Studio installed and configured it according to the support [guide](https://ionicframework.com/docs/developer-resources/platform-setup/mac-setup.html). In the output I just did 'ionic cordova compile --verbose' but I prepared beforehand and did cordova build as well.

**Output:**
```
MacBook-Pro:test Michael$ ionic cordova compile --verbose
[DEBUG] Reason for not using local CLI: LOCAL_CLI_NOT_FOUND
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: '/Users/Michael/Google Drive OGVO/Romereis 2018/Werkgroep 4: Rome boekje/App/test', local: false, 
        binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: 
        '/usr/local/lib/node_modules/ionic/dist/index.js' }
[DEBUG] Daemon found (pid: 2996)

? What platform would you like to compile (android, ios): android
> cordova compile android
ANDROID_HOME=/Users/Michael/Library/Android/sdk/
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home
Subproject Path: CordovaLib
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Error: /Users/Michael/Google Drive OGVO/Romereis 2018/Werkgroep 4: Rome boekje/App/test/platforms/android/gradlew: Command failed with exit code 1 Error output:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

[ERROR] An error occurred while running cordova compile android (exit code 1).
```

**My `ionic info`:**

```
MacBook-Pro:test Michael$ ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v7.8.0
    npm               : 4.2.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/Michael/Library/Android/sdk/

Misc:

    backend : pro
```

**Comment by dwieeb** [comment]
@BLX-S It's because of the colon in your folder path. More info: https://github.com/ionic-team/ionic-cli/issues/478

**Comment by kennethross** [comment]
Hi there. Im having the same issues. But I dont think mine is because of colon. 

output: 

 cordova build android
cordova-android-support-gradle-release: Android platform: V7+
cordova-android-support-gradle-release: Wrote custom version '27.+' to /Users/kenneth/Documents/Ionic/tn-crew-app/platforms/android/app/build.gradle
cordova-android-support-gradle-release: Wrote custom version '27.+' to /Users/kenneth/Documents/Ionic/tn-crew-app/platforms/android/cordova-android-support-gradle-release/tncrew-cordova-android-support-gradle-release.gradle
Android Studio project detected
cordova-android-support-gradle-release: Android platform: V7+
cordova-android-support-gradle-release: Wrote custom version '27.+' to /Users/kenneth/Documents/Ionic/tn-crew-app/platforms/android/app/build.gradle
cordova-android-support-gradle-release: Wrote custom version '27.+' to /Users/kenneth/Documents/Ionic/tn-crew-app/platforms/android/cordova-android-support-gradle-release/tncrew-cordova-android-support-gradle-release.gradle
ANDROID_HOME=/Users/kenneth/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home
studio
Subproject Path: CordovaLib
Subproject Path: app
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
/Users/kenneth/Documents/Ionic/tn-crew-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
