### ISSUE TITLE
CLI 4 - `address` option does not open the address.

### ISSUE THREAD

**Issue by thruthesky** [ionic-team/ionic-cli#3055]
**Description:**

I ran
````
$ ionic serve --address work.org
````

and I expected the web browser to have
````
http://work.org:8100
````
in its address bar.

But it shows
````
http://localhost:8100/
````

**My `ionic info`:**

```
cli packages: (/usr/local/lib/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.1
   ionic (Ionic CLI) : 4.0.0-rc.1

local packages:

   @angular-devkit/core       : 0.4.6
   @angular-devkit/schematics : 0.4.6
   @angular/cli               : 1.7.3
   @ionic/core                : 0.1.5
   Ionic Framework            : @ionic/angular 0.1.5

System:

   NodeJS : v8.9.4
   npm    : 3.10.10
   OS     : macOS High Sierra
```

**Comment by dwieeb** [comment]
@thruthesky The `--address` option specifies the server host to use, not which address to open. If the CLI can bind on the specified address, then the `localhost` address will always work locally, which is why it is opened. You'll find the Angular CLI has the same behavior with the `--host` option.

Do you expect to see `http://work.org:8100` because something in your app needs the `work.org` host to work?

**Comment by thruthesky** [comment]
@dwieeb Ah. I see. I understand. Thank you. and forgive my ignorance.

**Comment by dwieeb** [comment]
@thruthesky No problem, thanks for opening an issue! Please continue to do so for things that may seem wrong or confusing.
