### ISSUE TITLE
[Question] after v4 released, Is v3 left in CLI?

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-cli#3077]
**Description:**
After v3 released, v2 was not left in CLI.  I understood v3 is an extension of v2.

Now, I'm trying on v4. I know I can upgrade from v3 to v4. I feel that it is similar, but different Framework. So after v4 released, I want v3 left in CLI. 
I want to know what Ionic team think about this.

thanks.

**Comment by dwieeb** [comment]
Our versioning has been very strange.

I've been trying to _not_ use v1, v2, v3, v4 as terms because it's confusing. Instead, think of "project types" in terms of tooling.

**Ionic 1** (AngularJS): custom tooling w/ gulp and sass, custom livereload server
**Ionic Angular 2/3** (Angular 2+): custom tooling via `@ionic/app-scripts`
**Ionic Angular 4** (Angular 6+): Angular CLI for tooling

There is no upgrade path from v1 to v2--it's a totally different framework. 
The upgrade from v2 to v3 was a framework upgrade, but the tooling didn't change.
The upgrade from v3 to v4 will be a framework upgrade and a tooling change.

In the future, "v4" will become ambiguous. Does it refer to Ionic Angular 4? Ionic Stencil 4? Ionic React 4? So I like to think in terms of project types.

Right now, the CLI supports all three project types with the three types of tooling. I've seen people on the latest version of the CLI using Ionic Angular 2 by having an older version of `@ionic/app-scripts`. I try my best to support all versions of the Ionic Framework in the CLI because I believe people should have no reason _not_ to update to the latest CLI.

**Comment by rdlabo** [comment]
thanks for reply, and sorry for replying so late.

`project types` is  very easy to understand! and 

> I believe people should have no reason not to update to the latest CLI.

I really appreciate.
