### ISSUE TITLE
Change template order

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-cli#3183]
In 4.0.0-rc.6, when prompted to choose a template the order is:
tabs
blank
sidemenu

I think it should be in alphabetical order.

**Comment by dwieeb** [comment]
Would you expect the aws starter to be first in this list for `ionic start --type=ionic-angular`?

![image](https://user-images.githubusercontent.com/236501/40255328-6faea6f4-5aac-11e8-8531-b80856896e67.png)

**Comment by kensodemann** [comment]
FWIW, I would expect these in an order of generic usefulness, then alphabetical. I would keep the most generically useful on top, even if that breaks strict alphabetical order, because those are the ones most likely to be selected. So by that, `blank` would always be first since it is the most generic. Then `sidemenu` and `tabmenu`. Then all the special purpose ones.

So that would make:
blank
sidemenu
tabmenu
aws
super
tutorial
