### ISSUE TITLE
Live reload: changes in sass files lead to full page reloads (ionic4)

### ISSUE THREAD

**Issue by marcorinck** [ionic-team/ionic-cli#3521]
**Description:**
I'm currently trying to update my ionic3 app to ionic4 and experiencing an annoying behavior change when changing sass files now:  As was the case always for *.ts files (naturally) all changes in sass files now force the browser to do a full page reload of the app. This happens in the browser (ionic serve) and in the iOS emulator, too. 

Why is that? 

Ionic 3 updated the styles on the fly without reloading the whole page. As does a standard angular CLI project.  

This also happens in a newly created template project (from the tabs template), so it does not seem project-specific.

**My `ionic info`:**
```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.0.2
   ios-deploy        : 1.9.2
   ios-sim           : 2.0.1
   NodeJS            : v8.9.0 (/usr/local/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/mzrinck/Library/Android/sdk

```

**Comment by caio1985** [comment]
Same thing here. Frustrating...
```

Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.2 (/usr/local/bin/node)
   npm    : 6.13.7
   OS     : macOS Mojave

```

**Comment by mhartington** [comment]
Hey there! So Angular does not actually include HMR by default out of the box. You can test this yourself by including an input, typing something in that input, and modifying some CSS. The page will do a full refresh because the CLI will treat styles as a module.


In v3, css was treated as css and would just be injected in, so the page would not refresh. But since the ngCLI (which powers ionic/angular apps) does not behave like this, we get refresh. The ngCLI docs do mention HMR in there, but I have not tried it. 


Either way, this is not an issue with the Ionic CLI.
