### ISSUE TITLE
Passing an hostname to --address doesn't work after version 3.15.2

### ISSUE THREAD

**Issue by giorgio-cara** [ionic-team/ionic-cli#3557]
**Description:**
Up until version 3.15.2 included, when I pass a resolvable hostname using the option --address the browser automatically opens with that hostname in the URL. In newer versions the browser opens always with "localhost" in the URL.

**Steps to Reproduce:**
1) configure a hostname that resolves to 127.0.0.1 in the hosts file, let's call it "myhostname" in this example
2) install ionic CLI 3.15.2 with the command "npm i -g ionic@3.15.2"
3) run the command "ionic serve --address myhostname", the browser opens using "myhostname" in the URL
4) update the CLI to one of the next versions (version 4 included), for example with the command "npm i -g ionic@3.16.0"
3) run the command "ionic serve --address myhostname", now the browser opens using "localhost" in the URL instead of "myhostname"

**My `ionic info`:**

```
cli packages: (C:\Users\giorg\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

local packages:

    @ionic/app-scripts : 3.1.11
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.3
    npm  : 5.6.0
    OS   : Windows 10

Misc:

    backend : legacy
```

**Comment by dwieeb** [comment]
I think we should fix this with a `--public-host` option. More info: https://github.com/ionic-team/ionic-cli/issues/3440#issuecomment-409649358

**Comment by dwieeb** [comment]
@giorgio-cara I don't think we want to _always_ use `--address` for the URL in the browser. This was changed because the Ionic DevApp requires the Ionic CLI to use `0.0.0.0` (or a specific external network address) to work. But once the default changed to `0.0.0.0`, the browser opened `http://0.0.0.0`, and I wasn't sure of the implications of changing the default URLs of people's apps while they were developing using `ionic serve`.

I think we'll use `--address` for server host, and have it default to `0.0.0.0`. We'll use `--public-host` for the browser URL, and have it default to `localhost`. 

How does that sound?

**Comment by giorgio-cara** [comment]
That sounds like a more appropriate solution, thanks.

**Comment by dwieeb** [comment]
Closing in favor of this: https://github.com/ionic-team/ionic-cli/issues/3558
