### ISSUE TITLE
ionic resources should generate iPhone X splash screens

### ISSUE THREAD

**Issue by furkanedu** [ionic-team/ionic-cli#3585]
same as  #2904. 

Please do not close issues unless it is resolved. This ionic is sth people pay and expect sth from, if I had the chance I would ever never use this ionic. 

You guys close issues for no reason. This policy and bad software you have is showing the quality of IONIC.

**Comment by dwieeb** [comment]
One of the reasons we lock issues is when it is clear that our [Code of Conduct](https://github.com/ionic-team/ionic/blob/master/CODE_OF_CONDUCT.md) is not being followed, as with https://github.com/ionic-team/ionic-cli/issues/2904. 

The issue was re-created and closed by author here: https://github.com/ionic-team/ionic-cli/issues/2928#issuecomment-352595334.

Later I opened a more refined issue that tracks it: https://github.com/ionic-team/ionic-cli/issues/3319

Since this issue is also clearly in violation of our Code of Conduct, I will be closing and locking it. Please be constructive and do not resort to attacks. I would be happy to look at any PRs that resolve https://github.com/ionic-team/ionic-cli/issues/3319, but at the moment it is not being prioritized. Thank you!
