### ISSUE TITLE
Ionic 4 button tag issue

### ISSUE THREAD

**Issue by Ademking** [ionic-team/ionic-cli#3587]
**Description:**
Hello, when i'm creating a new project using the latest ionic-cli ...
`ionic start myApp tabs`

i tried to copy the code from here and use it
[https://beta.ionicframework.com/docs/components/#button
](https://beta.ionicframework.com/docs/components/#button)

```
<ion-button size="small">Small Button</ion-button>
```

then, when i try to use <ion-button> it shows :

```
'ion-button' is not a known element: 1. If 'ion-button' is an Angular component, then verify that it is part of this module. 2. If 'ion-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

after searching for solution i found this 
[https://stackoverflow.com/a/52208637](https://stackoverflow.com/a/52208637)

---------

So, why we need to write --angular every time we need to use <ion-button> tag ?
Thanks.

**Steps to Reproduce:**

1. ionic start myApp tabs
2. add this code to your page
`<ion-button size="small">Small Button</ion-button>`

**Comment by dwieeb** [comment]
The latest CLI creates a v3 app by default, because v4 is still in beta. You are using the v4 docs for a v3 app. You are probably looking for [these docs](https://ionicframework.com/docs/components/#buttons).

The default will change when v4 is out of beta. See also https://github.com/ionic-team/ionic-cli/issues/3597

**Comment by Ademking** [comment]
Thanks @dwieeb 👍
