### ISSUE TITLE
Ionic Lab Frame Device Choice

### ISSUE THREAD

**Issue by zoualmamy** [ionic-team/ionic-cli#3943]
any chance we can choose device frame in Ionic Lab in futur releases? 
That would help..

**Comment by dwieeb** [comment]
Related: https://github.com/ionic-team/ionic-cli/issues/3897

**Comment by PriceFallin** [comment]
I agree with this one. The current frames in ionic lab are way outdated and don't do us much good unless we're interested in seeing what the app looks like in an iPhone 5 or Galaxy 6 sized screen. We've obviously come a long way since those days. It would be nice to get some more current sizes/resolutions in the lab.

**Comment by JoaquimCAP** [comment]
I found the `--frame-default-width` attribute able to change the devices width and height in Ionic Lab preview, but is there any way to override that value from /theme/variables.scss ?
I can only change that value on my browser editing the :root css variables, but when I change that in Angular, after compilation, backs again to default value: 344px.
*Using Ionic 5 under Angular 10

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.
