### ISSUE TITLE
Ionic version should be explicit argument

### ISSUE THREAD

**Issue by bcaton85** [ionic-team/ionic-cli#4147]
Took more time than expected to find that `ionic start app blank --type=ionic-angular` creates an ionic 3 application while `--type=angular` creates an Ionic 4 application.This needs to be either an explicit argument or better documented.

**Comment by dwieeb** [comment]
It's in a lot of places:

- For starting Ionic 4 apps, people use the docs for v4: https://ionicframework.com/docs/building/starting
- For starting Ionic 3 apps, people use the docs for v3: https://ionicframework.com/docs/v3/intro/installation/
- It's in the `ionic start` docs: https://ionicframework.com/docs/cli/commands/start
- It's in the help output when you do `ionic start --help`
- It's in `ionic start --list`

We don't offer it as an "explicit" option because we highly recommend that new apps use Ionic 4 and we don't want to confuse beginners with an abundance of options. Of course, [our docs](https://github.com/ionic-team/ionic-docs) are on Github and we welcome PRs for improvements. 

Also, Ionic React will be out of RC soon and at that point we'll have a prompt for selecting which framework to use with Ionic. I could see the `ionic-angular` project type being mentioned here, possibly. See https://github.com/ionic-team/ionic-cli/issues/4118 for that.
