### ISSUE TITLE
bug: prompts are sometimes cut off and do not let me proceed

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-cli#4353]
**Description:**

When running certain commands that require prompts, they are sometimes cut off preventing me from proceeding.

**Steps to Reproduce:**

1. Get a project with an existing `capacitor.config.json` file that has old cordova settings (I attached an example below).
2. Run `ionic integrations enable capacitor`.
3. The CLI will ask `? capacitor.config.json already contains cordova preferences. Overwrite with val`. Notice that the sentence is cut off and you cannot type a response.

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.2.2 (/Users/liamdebeasi/.nvm/versions/node/v10.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.0, (and 5 other plugins)

Utility:

   cordova-res (update available: 0.10.0) : 0.6.0
   native-run (update available: 0.3.0)   : 0.2.7

System:

   Android SDK Tools : 26.1.1 (/Users/liamdebeasi/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.15.0 (/Users/liamdebeasi/.nvm/versions/node/v10.15.0/bin/node)
   npm               : 6.9.2
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504

```

**Other Information:**

Here is a sample config file that I am using:

```
{
  "appId": "io.ionic.starter",
  "appName": "ionic-conference-app",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "www",
  "cordova": {
    "preferences": {
      "ScrollEnabled": "false",
      "android-minSdkVersion": "19",
      "BackupWebStorage": "none",
      "SplashMaintainAspectRatio": "true",
      "FadeSplashScreenDuration": "300",
      "SplashShowOnlyFirstTime": "false",
      "SplashScreen": "screen",
      "SplashScreenDelay": "3000"
    }
  }
}
```

**Comment by ltm** [comment]
**Steps to Reproduce:**
```
ionic start CapdovaApp blank --cordova --no-link --type=angular --no-interactive --confirm
cd capdovaApp

npm install @capacitor/core @capacitor/cli
npx cap init CapdovaApp io.ionic.starter --npm-client npm

ionic capacitor sync ios
```

**Comment by jcesarmobile** [comment]
The problem is you are manually integrating Capacitor instead of using `ionic integrations enable capacitor`.
As `ionic capacitor sync ios` checks for the integration in `ionic.config.json` and it says it's not integrated, it tries to integrate it again with `ionic integrations enable capacitor`.
But as it was manually integrated, there is a `capacitor.config.json` file present, so capacitor ask for overwriting it. As Ionic CLI runs Capacitor CLI in a non interactive way, it hangs waiting for the answer. 

I think Ionic CLI should check if a `capacitor.config.json` file is present before calling `ionic integrations enable capacitor` internally, and if present, just mark the project as integrated in `ionic.config.json`.

If not possible, Capacitor CLI should be updated to not prompt (but what should it do, overwrite or not?). Or allow some param that could be passed to overwrite or not based on it.
