### ISSUE TITLE
Cannot install Ionic Auth Connect - 404 Not Found

### ISSUE THREAD

**Issue by Ric43** [ionic-team/ionic-cli#4358]
Trying to install Auth Connect to enable OAuth2 integration. Following the instructions on the docs pages here:

https://ionicframework.com/docs/enterprise/auth-connect

For capacitor, I run:

npm install @ionic-enterprise/auth

Response is:
npm ERR! A complete log of this run can be found in:
<Prompt> npm install @ionic-enterprise/auth
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ionic-enterprise%2fauth - Not found
npm ERR! 404
npm ERR! 404  '@ionic-enterprise/auth@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by dotNetkow** [comment]
Hi there - did you register an enterprise key first? See [first time setup steps here](https://ionicframework.com/docs/enterprise/setup).

**Comment by ch4mpy** [comment]
Hello,
I did register, registered my app too (linked to github repo) and finally logged in with the CLI (`ionic login`) but get the same error.

**Comment by dotNetkow** [comment]
Did you register your [Native Key](https://ionicframework.com/docs/enterprise/setup#register-your-product-key) with `ionic enterprise register`?

**Comment by tharrington** [comment]
@dotNetkow I do not have the native keys available in my hub. Are the ionic native plugins no longer available?

**Comment by dotNetkow** [comment]
Hi @tharrington and everyone, I'll try to clarify when I meant earlier.

Ionic Auth Connect makes it easy to add authentication to your Ionic app - Azure AD, AWS, Auth0 and more. It's a paid solution, meaning you/your company must purchase a license key from Ionic. Otherwise, you'll get a 404 or similar error when you try to "npm install" any of these plugin solutions. To get access/learn more, please [fill out this form](https://ionicframework.com/sales).
