### ISSUE TITLE
ionic info wrong (npm not found)

### ISSUE THREAD

**Issue by moobsen** [ionic-team/ionic-cli#4458]
**Description:**
When I'm doing

> ionic info

I get the following (wrong) output

```
Ionic:

   Ionic CLI : 6.10.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.4.0
   npm    : not installed
   OS     : Linux 5.4
```

**Steps to Reproduce:**
npm install -g @ionic/cli
ionic info

**Other Information:**
I'm on Xubuntu 20.04 LTS and install node via snap
`sudo snap install node --channel=14 --classic`

```
which npm
/home/mo/.node/bin/npm
```
```
which node
/snap/bin/node
```

**Comment by Marlrus** [comment]
I am getting the same issue on Ubuntu 19.10

Running ionic info I am getting:

`Ionic:

   Ionic CLI : 6.10.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.14.0
   npm    : not installed
   OS     : Linux 5.3

`
**Other Info:**

I also installed node via snap.

node version
`v13.14.0
`

npm version 
`6.14.4
`
Running ionic start myApp blank --type=react 

Yields 
`> npm i --save -E @capacitor/core
[ERROR] An error occurred while running subprocess npm.
`

I'm guessing because of the npm not installed error. No ionic script works using the cli on the project either.

**Comment by moobsen** [comment]
This might not really be an ionic bug. I'm not entirely sure yet what causes this. It probably has something to do with snap and unusual  paths.
`npm --scripts-prepend-node-path=true start`
works for me, while "ionic serve" fails.
As a workaround you can add npm scripts to the package.json and run them with npm and the --scripts-prepend-node-path=true flag.
E.g. adding
`"ioninfo": "ionic info"`
in the scripts section of the **package.json** and running
`npm --scripts-prepend-node-path=true run-script ioninfo`
gives the expected output.

**Comment by Marlrus** [comment]
I agree that it probably has to do with the snap installation. However my issue is not directly with `ionic serve` I can serve my start script with `npm run start` or `yarn start` . This is the err I get on `ionic serve`

```
ionic serve --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/bash', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'serve' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +5ms
  ionic:lib:project Project type from config: @ionic/react (react) +0ms
  ionic:lib:project Project details: { configPath: '/home/marlrus/webDev/learning/ionic/ionicTest/ionic.config.json', errors: [], context: 'app', type: 'react' } +1ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/usr/local/lib/node_modules/@ionic/cli', execPath: '/home/marlrus/webDev/learning/ionic/ionicTest', version: '6.10.0' } +0ms
  ionic:lib:serve serve options: {
  ionic:lib:serve   '--': [],
  ionic:lib:serve   host: 'localhost',
  ionic:lib:serve   browser: undefined,
  ionic:lib:serve   browserOption: undefined,
  ionic:lib:serve   engine: 'browser',
  ionic:lib:serve   externalAddressRequired: false,
  ionic:lib:serve   lab: false,
  ionic:lib:serve   labHost: 'localhost',
  ionic:lib:serve   labPort: 8200,
  ionic:lib:serve   livereload: true,
  ionic:lib:serve   open: true,
  ionic:lib:serve   platform: undefined,
  ionic:lib:serve   port: 8100,
  ionic:lib:serve   proxy: true,
  ionic:lib:serve   project: undefined,
  ionic:lib:serve   publicHost: undefined,
  ionic:lib:serve   verbose: true,
  ionic:lib:serve   ci: undefined,
  ionic:lib:serve   https: undefined,
  ionic:lib:serve   reactEditor: undefined
  ionic:lib:serve } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic serve' [ '--verbose', '--interactive', '--color' ] +0ms
  ionic:lib:hooks Looking for ionic:serve:before npm script. +0ms
  ionic:utils-network checking for open port on 0.0.0.0:8100 +0ms
  ionic:utils-network checking for open port on 127.0.0.1:8100 +8ms
  ionic:utils-network checking for open port on ::1:8100 +0ms
  ionic:utils-network checking for open port on 192.168.0.18:8100 +2ms
  ionic:utils-network checking for open port on fe80::6abb:6a39:236:5b66:8100 +0ms
  ionic:utils-network error while checking fe80::6abb:6a39:236:5b66:8100: Error: listen EINVAL: invalid argument fe80::6abb:6a39:236:5b66:8100     at Server.setupListenHandle [as _listen2] (net.js:1296:21)     at listenInCluster (net.js:1361:12)     at doListen (net.js:1498:7)     at processTicksAndRejections (internal/process/task_queues.js:85:21) { code: 'EINVAL', errno: -22, syscall: 'listen', address: 'fe80::6abb:6a39:236:5b66', port: 8100 } +2ms
  ionic:lib:serve Looking for ionic:serve npm script. +38ms
> react-scripts start
  ionic:lib:serve received unexpected close for react-scripts (code: 1) +2s

[ERROR] react-scripts has unexpectedly closed (exit code 1).
        
        The Ionic CLI will exit. Please check any output above for error details.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions 
```

I'm not getting the dependencies installed correctly due to Ionic CLI not finding npm and there are no docs on installation of packages without using the Ionic CLI. Although I can get a basic app running I cannot do any of the important things.

`ionic integrations enable capacitor` will err and not work: 

```
ionic integrations enable capacitor --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/bash', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'integrations', 'enable', 'capacitor' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +5ms
  ionic:lib:project Project type from config: @ionic/react (react) +0ms
  ionic:lib:project Project details: { configPath: '/home/marlrus/webDev/learning/ionic/ionicTest/ionic.config.json', errors: [], context: 'app', type: 'react' } +1ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/usr/local/lib/node_modules/@ionic/cli', execPath: '/home/marlrus/webDev/learning/ionic/ionicTest', version: '6.10.0' } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic integrations enable' [ 'capacitor', '--verbose', '--interactive', '--color' ] +0ms
> npm i --save -E @capacitor/core
[ERROR] An error occurred while running subprocess npm.
        
        npm i --save -E @capacitor/core exited with exit code 243.
        
        Re-running this command with the --verbose flag may provide more
        information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +32ms
```

I worked around this with `npm install @capacitor/core @capacitor/cli` and then running `npx cap init`

I installed the packages manually but I couldn't get it to work because running `ionic build` runs but doesn't create any directory www/ for capacitor. I switched it to the build/ dir that was created by ionic build but it errd anyway. 

`ionic cap add ios` and `ionic cap add android` are also always erring with the same message above `[ERROR] An error occurred while running subprocess npm.` . After the workaround I get a different error

```
ionic cap add android --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/bash', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cap', 'add', 'android' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +4ms
  ionic:lib:project Project type from config: @ionic/react (react) +0ms
  ionic:lib:project Project details: { configPath: '/home/marlrus/webDev/learning/ionic/ionicTest/ionic.config.json', errors: [], context: 'app', type: 'react' } +0ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/usr/local/lib/node_modules/@ionic/cli', execPath: '/home/marlrus/webDev/learning/ionic/ionicTest', version: '6.10.0' } +0ms
> capacitor add android
  ionic:lib:telemetry Sending telemetry for command: 'ionic capacitor add' [ 'android', '--verbose', '--interactive', '--color' ] +0ms
[error] Capacitor could not find the web assets directory "/home/marlrus/webDev/learning/ionic/ionicTest/www".
    Please create it, and make sure it has an index.html file. You can change
    the path of this directory in capacitor.config.json.
    More info: https://capacitor.ionicframework.com/docs/basics/configuring-your-app
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor add android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more
        information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +65ms
```

Ionic can't run the npm script, the capacitor CLI, or react scripts. But I am yet to find any documentation that lets you create a working project without using the Ionic CLI, as almost every process depends on it. 

**Only working script not working as expected**

Running `ionic build` works, however seeing the docs it says:

> This creates the www folder that Capacitor has been automatically configured to use as the webDir in capacitor.config.json.

Which is untrue in my case. It just creates a build/ directory the same as if I would have run `npm run build` or `yarn build` and not get the www/ directory.

**Troubleshooting**

I have tried to alter all the configurations files for ionic in **~/.ionic/config.json**, the path in my environmental variables for npm, the npm config file. Everything. I am yet to find a way to manually set the npm path for the Ionic CLI anywhere. So I don't believe I can do anything correctly without the Ionic CLI detecting npm.

I have also re installed npm a few times, cleared the cache. I have uninstalled and installed the Ionic CLI about 5 times as well. 

I really want to work using Ionic! It is a fantastic tool and what I've gotten to code with just the UI Ionic Components has been super simple and looks amazing. I just can't get any capacitor/native integration working without the CLI working.

Cheers!

**Comment by dreadnought** [comment]
I've bypassed this issue by removing the node snap package and installing the debian package from the PPA:
https://github.com/nodesource/distributions/blob/master/README.md#debinstall

**Comment by moobsen** [comment]
Closing this, as this seems to be a packaging issue and nothing related to ionic itself.
