### ISSUE TITLE
Ionic + capacitor + vue on Android 8.1 White Screen

### ISSUE THREAD

**Issue by JnNanghty** [ionic-team/ionic-cli#4712]
**Description:**
ionic在安卓8.1下发生白屏。  
我用Chrome的 chrome://inspect/#devices  测试之后发现，ion-app, ion-content, etc. 这些标签的 visibility 为 hidden，而且没有用别的css style 去覆盖他。 ion-app 等 这些标签的class 都是空的， 没有 md hydrated。 而在 android 高版本则正常的。

**Steps to Reproduce:**
1、 yarn build打包项目，生成dist
2、 yarn cap copy 到 capacitor 生成的android项目中
3、 使用 AVD Manager 创建一个android8.1 (API 27)的虚拟机
4、 build and run

**Output:**
No error, only a white screen

**Other Information:**
因为在发布到应用市场的时候， 应用市场的测试人员使用的环境是android8.1， 结果没通过， 所以debug之后发现了这个问题。
然后在一些低版本的安卓上使用的 webview 或许是不支持 viewport，会显示得很大，即使设置了webView.getSettings().setUseWideViewPort(true);   webView.getSettings().setLoadWithOverviewMode(true);
也不起作用。  不过升级了 webview 问题就解决了。 
还有在 ios 系统部分下（可能是12或以下）， 只要发生点击事件， 在深色背景的地方就会出现闪烁，像是显示了最上层（可能是body标签）的白色的背景。 但是在 ios14 就没有这样的问题。

**Comment by JnNanghty** [comment]
我自己觉得像是 webview 的setting问题，  android 之前的版本或许有不支持的 webview 设置。

**Comment by jcesarmobile** [comment]
Please, when creating issues, use English. We don't understand Chinese.

Capacitor 3 requires Chrome/Chromium/System WebView 60 or greater, check navigator.userAgent value when debugging your app, you probably have an older version.

Since you are in Android 8.1, the WebView is supposed to use the same version as Chrome, so update Chrome if you can. Sadly not all vendors implemented the updatable WebView, so it's possible that even if you update Chrome your app still uses an older version, and also I've heard that play store is blocked in China, so it's possible that you won't be able to update.
