### ISSUE TITLE
Adding Android compiler parameters - running crosswalk with requires Android SDK >= 15

### ISSUE THREAD

**Issue by sagivf** [ionic-team/ionic-cli#662]
Some projects need to run with -- --minSdkVersion=15.

--minSdkVersion is not a parameter that cordova-cli understands but rather the Android compiler. 
so running `ionic build android -- --minSdkVersion=15` works.
but running `ionic run android -l -c -s -- --minSdkVersion=15` does not work, so you can't use live reload.

**Comment by joelbowen** [comment]
+1 I'm working through an issue with this right now, @sagivf how did you solve yours?

**Comment by sagivf** [comment]
no man - glad to see I'm not alone :) .
still have to use the minSdkVersion, still no no live reload. Still no response...

**Comment by joelbowen** [comment]
What version of cordova are you using? I updated to 6.1.1 and am having slightly better luck.

**Comment by sagivf** [comment]
6.0.0, i'll try to upgrade. So what is your status? All is working for you?

**Comment by joelbowen** [comment]
Yes, It is working now with livereload. I am having an issue removing the FB plugin but I believe it is unrelated.

I did multiple things leading up to this solution, which I can try to step through again if your issue is still unresolved. But I think it was the CLI version change the finally fixed things. `npm update -g cordova`

[https://cordova.apache.org/docs/en/latest/guide/cli/index.html](https://cordova.apache.org/docs/en/latest/guide/cli/index.html)
