### ISSUE TITLE
Wrong version of cordova-ios when auto-adding ios platform

### ISSUE THREAD

**Issue by ccoenraets** [ionic-team/ionic-cli#725]
With the latest CLIs, doing:

```
cordova create test
cordova platforms add ios
cd test
cordova platforms
```

shows cordova-ios 3.9.2

However:

```
ionic start test
cd test
ionic platforms
```

**shows cordova-ios 3.8.0**

You can then update to 3.9.2 with:

```
ionic platforms update ios
```

or...

```
ionic platforms remove ios
ionic platforms add ios
```

also gives me 3.9.2

When auto-adding iOS, is there a reason the ionic CLI doesn't default to the latest version of cordova-ios?

**Comment by mirkonasato** [comment]
Similar issue here. And with the auto-added ios platform the icon and splash screen images are the Cordova ones instead of the Ionic ones, and the app name sometimes appear as `HelloCordova` instead of the project name.

    $ ionic start my-app blank
    Adding in iOS application by default
    $ cd my-app
    $ ionic platform list
    Installed platforms: ios 3.8.0

Removing and re-adding the platform seems to fix everything.

    $ ionic platform rm ios
    $ ionic platform add ios
    $ ionic platform list
    Installed platforms: ios 4.0.1

and the images are the Ionic ones.

To be honest I'm not sure why `ios` is added by default when `android` is not, it's inconsistent. I would rather have no platforms by default.

Full versions:

	$ ionic info

	Your system information:

	Cordova CLI: 6.0.0
	Gulp version:  CLI version 3.9.0
	Gulp local:
	Ionic Version: 1.2.4
	Ionic CLI Version: 1.7.14
	Ionic App Lib Version: 0.7.0
	ios-deploy version: 1.8.4
	ios-sim version: 5.0.6
	OS: Mac OS X El Capitan
	Node Version: v4.2.6
	Xcode version: Xcode 7.2 Build version 7C68

**Comment by redfox05** [comment]
@mirkonasato I agree, IOS should not be added by default. Otherwise, why not android.
But im concerned if you have an issue with the ios auto adding. Does this mean it could also not properly remove ios using "ionic platform remove ios"

Basically, we need just an android app, so have no need for ios. In fact right now, we just want a Cordova webview wrapper. So neither Android or IOS.

I have created another issue specifically to removing the IOS by default behaviour: https://github.com/driftyco/ionic-cli/issues/799

**Comment by mirkonasato** [comment]
Removing with `ionic platform rm ios` works fine, and if you re-add it with `ionic platform add ios` then everything works as expected. It's only when the ios platform is auto-added on project creation that it behaves oddly.
