### ISSUE TITLE
Generator with existing entities

### ISSUE THREAD

**Issue by maxx0r** [ionic-team/ionic-cli#968]
Hi,

first off; i'm an idiot.

I generated a file, wrote the code, wanted to start the serve job and in a reflex I did arrow up+ enter in my command prompt.

But i forgot i didnt ionic serve after generating. So it regenerated the page, overwriting the code I just wrote. Is there a possibility the generator checks whether the generate command will overwrite existing files so it can ask for a confirmation?

**Comment by tlancina** [comment]
Hey thanks for the issue. I think this is definitely a good idea, for the
exact situation you encountered.

**Comment by goleary** [comment]
D'oh! I just did this exact same thing.

Seems like this would be a super simple fix that would prevent people like myself & max from banging our heads on tables in the future.

**Comment by dwieeb** [comment]
Huh.. I must've closed the tab before writing a comment. Sorry about that.

We won't be adding this functionality for v3. We're only putting critical fixes into `@ionic/app-scripts`. That's why I closed this issue. 

If you like I can keep the issue open for v4, but for v4 the Ionic CLI uses the Angular CLI to run schematics that generate app features. The feature request would have to be made in the [Angular CLI repo](https://github.com/angular/angular-cli), because it would be for `ng generate`.

**Comment by goleary** [comment]
I'm pretty sure angular-cli already does this (at least for the last version I used of it that was the case)

**Comment by goleary** [comment]
![image](https://user-images.githubusercontent.com/16123225/43345524-a67059d0-91a2-11e8-91f4-5c63a2a8a91f.png)
IIRC this has been the effect for some time.

**Comment by dwieeb** [comment]
Oops, sorry. I thought we were talking about the original feature request:

> Is there a possibility the generator checks whether the generate command will overwrite existing files so it can ask for a confirmation?

I think the error message is good, though. 👍
